name: AgentScan

on:
  pull_request_target:
    types:
      - opened
      - reopened
  issues:
    types:
      - opened

jobs:
  agentscan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
    steps:
      - name: AgentScan
        uses: MatteoGabriele/agentscan-action@02703f83efe371275cca23c319956d8fdbc62fa5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-organic: true
